
name: WZKRice CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tron:
        description: 'Run TronScript'
        required: false
        type: boolean
jobs:
  install:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            main.bat
            scripts
            .github
      - name: Auto-setup
        run: |
          cmd /c call "$PWD/scripts/SetKeyValue" RunTronScript ${{ inputs.tron == true && 1 || 0 }} "$PWD/config.ini"
          cmd /c "$PWD/.github/workflows/autosetup.bat"
